apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wishlists
  labels:
    app: wishlists
spec:
  rules:
  - host: cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wishlists
            port:
              number: 8080

